hunav_loader:
  ros__parameters:
    map: cafe
    publish_people: true
    agents:
      - agent1
      - agent2
      - agent3
    agent1:
      id: 1
      skin: 2
      behavior: 5
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      init_pose:
        x: -3.973340
        y: -8.576801
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: -3.133759
        y: -4.166653
        h: 1.250000
      g1:
        x: 0.997901
        y: -4.131655
        h: 1.250000
      g2:
        x: -0.227549
        y: -10.187146
        h: 1.250000
    agent2:
      id: 2
      skin: 3
      behavior: 6
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      init_pose:
        x: 2.924233
        y: 5.007970
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: -2.644067
        y: 2.066231
        h: 1.250000
      g1:
        x: -1.663169
        y: -3.291318
        h: 1.250000
      g2:
        x: 3.344481
        y: 1.470876
        h: 1.250000
    agent3:
      id: 3
      skin: 1
      behavior: 4
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      init_pose:
        x: 0.507801
        y: 1.330791
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: -3.239419
        y: -1.786054
        h: 1.250000
      g1:
        x: -2.222970
        y: -7.316537
        h: 1.250000
      g2:
        x: 3.203787
        y: -3.536413
        h: 1.250000