hunav_loader:

# Behaviors:
# BEH_REGULAR=1
# BEH_IMPASSIVE=2
# BEH_SURPRISED=3
# BEH_SCARED=4
# BEH_CURIOUS=5
# BEH_THREATENING=6

  ros__parameters:
    # GLOBAL PARAMS
    # 2D image map to be loaded.
    # A Distance Transform will be created. 
    map: 'cafe'
    #base_world: cafe

    publish_people: true

    # AGENTS
    agents: 
      - 'agent1'
      - 'agent2'

      # agent 1
    agent1:
      id: 1
      skin: 1
      behavior: 5
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      init_pose:
        x: -1.0
        y: 2.0
        z: 1.25
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - 'g1'
        - 'g2'
        - 'g3'
      g1:
        x: -1.0
        y: -8.0
        h: 1.25
      g2:
        x: -1.0
        y: 2.0
        h: 1.25
      g3:
        x: 2.8
        y: 0.5
        h: 1.15
      
    agent2:
      id: 2
      skin: 2
      behavior: 3
      group_id: -1
      max_vel: 1.1
      radius: 0.4
      init_pose:
        x: 3.0
        y: 0.0
        z: 1.25
        h: 1.57
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - 'g1'
        - 'g2'
        - 'g3'
      g1:
        x: -1.0
        y: 2.0
        h: 1.25
      g2:
        x: -1.0
        y: -8.0
        h: 1.25
      g3:
        x: 2.8
        y: 0.5
        h: 1.15

        


    
